apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-headless-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-headless
  template:
    metadata:
      labels:
        app: nginx-headless
    spec:
      containers:
      - name: nginx
        image: nginx-hello-world:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
spec:
  selector:
    app: nginx-headless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  clusterIP: None